openapi: 3.0.3
info:
  title: telephony_providers API
  description: okta telephony_providers API
  version: 2026.07.2
paths:
  /api/v1/telephony-providers:
    get:
      summary: List all custom telephony providers
      description: Lists all custom telephony providers that are configured in your org
      operationId: listAllCustomTelephonyProviderCredentials
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/ListAllCustomTelephonyProviderCredentialsResponse
              examples:
                CustomTelephonyProviderCredentialsListAllResponseEx:
                  $ref: >-
                    #/components/examples/CustomTelephonyProviderCredentialsListAllResponseEx
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
      security:
        - apiToken: []
        - oauth2:
            - okta.customTelephonyProvider.read
      tags:
        - CustomTelephonyProvider
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
    post:
      summary: Create a custom telephony provider
      description: Creates a custom telephony provider with the provided credentials
      operationId: createCustomTelephonyProviderCredentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/CustomTelephonyProviderCredentialCreateRequest
            examples:
              CustomTelephonyProviderCredentialCreateRequestExTwilio:
                $ref: >-
                  #/components/examples/CustomTelephonyProviderCredentialCreateRequestTwilioEx
              CustomTelephonyProviderCredentialCreateRequestExTelesign:
                $ref: >-
                  #/components/examples/CustomTelephonyProviderCredentialCreateRequestTelesignEx
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomTelephonyProviderCredentialResponse'
              examples:
                CustomTelephonyProviderCredentialCreateResponseTwilioEx:
                  $ref: >-
                    #/components/examples/CustomTelephonyProviderCredentialCreateResponseTwilioEx
                CustomTelephonyProviderCredentialCreateResponseTelesignEx:
                  $ref: >-
                    #/components/examples/CustomTelephonyProviderCredentialCreateResponseTelesignEx
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
      security:
        - apiToken: []
        - oauth2:
            - okta.customTelephonyProvider.manage
      tags:
        - CustomTelephonyProvider
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
  /api/v1/telephony-providers/{customTelephonyProviderId}:
    get:
      summary: Retrieve a custom telephony provider
      description: Retrieves the details of a custom telephony provider by its ID
      operationId: getCustomTelephonyProviderCredential
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomTelephonyProviderCredentialResponse'
              examples:
                CustomTelephonyProviderCredentialsListOneResponseEx:
                  $ref: >-
                    #/components/examples/CustomTelephonyProviderCredentialListOneResponseEx
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
      security:
        - apiToken: []
        - oauth2:
            - okta.customTelephonyProvider.read
      tags:
        - CustomTelephonyProvider
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
      parameters:
        - $ref: '#/components/parameters/customTelephonyProviderId'
    patch:
      summary: Update a custom telephony provider credential
      description: Updates the credentials of an existing custom telephony provider
      operationId: updateCustomTelephonyProviderCredential
      parameters:
        - $ref: '#/components/parameters/customTelephonyProviderId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/CustomTelephonyProviderCredentialUpdateRequest
            examples:
              CustomTelephonyProviderCredentialUpdateRequestEx:
                $ref: >-
                  #/components/examples/CustomTelephonyProviderCredentialUpdateRequestEx
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomTelephonyProviderCredentialResponse'
              examples:
                CustomTelephonyProviderCredentialsUpdateResponseEx:
                  $ref: >-
                    #/components/examples/CustomTelephonyProviderCredentialsUpdateResponseEx
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
      security:
        - apiToken: []
        - oauth2:
            - okta.customTelephonyProvider.manage
      tags:
        - CustomTelephonyProvider
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
    delete:
      summary: Delete a custom telephony provider
      description: >-
        Deletes a custom telephony provider by its ID.


        Before you delete a provider, ensure that it is
        [deactivated](https://developer.okta.com/docs/api/openapi/okta-management/management/customtelephonyprovider/deactivatecustomtelephonycredential).
        Consider setting up another telephony provider if you still plan to use
        telephony in your org. See [Set up an external telephony
        provider](https://help.okta.com/okta_help.htm?type=oie&id=about-telephony).
      operationId: deleteCustomTelephonyProviderCredential
      parameters:
        - $ref: '#/components/parameters/customTelephonyProviderId'
      responses:
        '204':
          description: No Content
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
      security:
        - apiToken: []
        - oauth2:
            - okta.customTelephonyProvider.manage
      tags:
        - CustomTelephonyProvider
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
  /api/v1/telephony-providers/{customTelephonyProviderId}/lifecycle/activate:
    post:
      summary: Activate a custom telephony provider
      description: >-
        Activates a custom telephony provider by its ID. You must activate a
        provider before it can be used.
      operationId: activateCustomTelephonyCredential
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomTelephonyProviderCredentialResponse'
              examples:
                CustomTelephonyProviderCredentialListOneResponseEx:
                  $ref: >-
                    #/components/examples/CustomTelephonyProviderCredentialListOneResponseEx
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
      security:
        - apiToken: []
        - oauth2:
            - okta.customTelephonyProvider.manage
      tags:
        - CustomTelephonyProvider
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
      parameters:
        - $ref: '#/components/parameters/customTelephonyProviderId'
  /api/v1/telephony-providers/{customTelephonyProviderId}/lifecycle/deactivate:
    post:
      summary: Deactivate a custom telephony provider
      description: >-
        Deactivates a custom telephony provider by its ID. Keep the following
        points in mind when you deactivate a provider:

        * You must deactivate a provider before deleting it.

        * If you have two telephony providers configured, and both are active,
        you can only deactivate the secondary provider. The second provider is
        the one that isn't set as the primary provider.
      operationId: deactivateCustomTelephonyCredential
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomTelephonyProviderCredentialResponse'
              examples:
                CustomTelephonyProviderCredentialDeactivatedResponseEx:
                  $ref: >-
                    #/components/examples/CustomTelephonyProviderCredentialDeactivatedResponseEx
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
      security:
        - apiToken: []
        - oauth2:
            - okta.customTelephonyProvider.manage
      tags:
        - CustomTelephonyProvider
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
      parameters:
        - $ref: '#/components/parameters/customTelephonyProviderId'
  /api/v1/telephony-providers/{customTelephonyProviderId}/setAsPrimary:
    post:
      summary: Set a custom telephony provider as a primary telephony provider
      description: >-
        Sets a custom telephony provider as the primary telephony provider for
        the org. You can only set one provider as a primary provider at a time.
      operationId: setAsPrimaryCustomTelephonyCredential
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomTelephonyProviderCredentialResponse'
              examples:
                CustomTelephonyProviderCredentialPrimaryResponseEx:
                  $ref: >-
                    #/components/examples/CustomTelephonyProviderCredentialPrimaryResponseEx
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
      security:
        - apiToken: []
        - oauth2:
            - okta.customTelephonyProvider.manage
      tags:
        - CustomTelephonyProvider
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
      parameters:
        - $ref: '#/components/parameters/customTelephonyProviderId'
  /api/v1/telephony-providers/{customTelephonyProviderId}/test:
    post:
      summary: Send a test message from a custom telephony provider
      description: >-
        Sends a test message (SMS or call) using the specified custom telephony
        provider to verify that the provider is configured correctly.


        You must provide a valid phone number and country code to send the test
        message. Send it to a phone number that you have access to so you can
        confirm that the message was received.
      operationId: sendTestCustomTelephonyProviderCredential
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/CustomTelephonyProviderCredentialSendTestRequest
            examples:
              CustomTelephonyProviderCredentialSendTestRequestEx:
                $ref: >-
                  #/components/examples/CustomTelephonyProviderCredentialSendTestRequestEx
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
      security:
        - apiToken: []
        - oauth2:
            - okta.customTelephonyProvider.manage
      tags:
        - CustomTelephonyProvider
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
      parameters:
        - $ref: '#/components/parameters/customTelephonyProviderId'
components:
  schemas:
    CustomTelephonyProviderCredentialsResponse:
      description: Response for credentials of multiple custom telephony providers
      items:
        $ref: '#/components/schemas/CustomTelephonyProviderCredentialResponse'
      type: array
    CustomTelephonyProviderCredentialCreateRequest:
      description: Create custom telephony provider credentials
      properties:
        providerAuthToken:
          type: string
          description: >-
            The authentication token that's used to authenticate requests to the
            telephony provider. Your telephony provider gives you this token.
        providerCapability:
          type: string
          description: >-
            The types of telephony operations (SMS or Voice) that you use with
            your telephony provider.


            `ALL` is the only valid value. It indicates that your provider can
            handle both SMS messages and voice calls. You're not required to use
            both types of telephony operations, but your provider can support
            both.
          enum:
            - ALL
        providerName:
          type: string
          description: The name of the telephony provider
          enum:
            - TWILIO
            - TELESIGN
        providerSettings:
          $ref: '#/components/schemas/CustomTelephonyProviderSettings'
        providerSid:
          type: string
          description: >-
            The account string identifier (SID) for your telephony provider
            account. Your telephony provider gives you this SID.
      type: object
    CustomTelephonyProviderCredentialResponse:
      type: object
      properties:
        enabled:
          type: boolean
          description: Indicates whether the provider is enabled and can be used
        id:
          type: string
          description: ID of the custom telephony provider
        isPrimaryProvider:
          type: boolean
          description: Indicates whether the provider is the primary telephony provider
        providerCapability:
          type: string
          description: >-
            The types of telephony operations (SMS or Voice) that you use with
            your telephony provider.


            `ALL` is the only valid value. It indicates that your provider can
            handle both SMS messages and voice calls. You're not required to use
            both types of telephony operations, but your provider can support
            both.
          enum:
            - ALL
        providerName:
          type: string
          description: Name of the telephony provider
          enum:
            - TWILIO
            - TELESIGN
        providerSettings:
          $ref: '#/components/schemas/CustomTelephonyProviderSettings'
        providerSid:
          type: string
          description: >-
            The account string identifier (SID) for your telephony provider
            account. Your telephony provider gives you this SID.
    CustomTelephonyProviderCredentialUpdateRequest:
      description: Update custom telephony provider credentials
      type: object
      properties:
        id:
          type: string
          description: ID of the custom telephony provider
        providerAuthToken:
          type: string
          description: >-
            The authentication token that's used to authenticate requests to the
            telephony provider. Your telephony provider gives you this token.
        providerSettings:
          $ref: '#/components/schemas/CustomTelephonyProviderSettings'
        providerSid:
          type: string
          description: >-
            The account string identifier (SID) for your telephony provider
            account. Your telephony provider gives you this SID.
    CustomTelephonyProviderCredentialSendTestRequest:
      type: object
      properties:
        countryCodeIso2:
          type: string
          description: >-
            The country code for the phone number.

            Use the [Alpha-2 code from ISO
            3166-1](https://www.iso.org/obp/ui/#search) for country codes.
        factor:
          type: string
          description: The type of test message to send
          enum:
            - SMS
            - CALL
        phoneNumber:
          type: string
          description: The phone number to which the test message or call is sent
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: >-
            A unique identifier for this error. This can be used by Okta Support
            to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: >-
            A short description of what caused this error. Sometimes this
            contains dynamically-generated information about your specific
            error.
    CustomTelephonyProviderSettings:
      x-okta-ignore-redocly-rules-for-sdk: true
      description: >-
        Settings for custom telephony provider.


        These settings vary based on the telephony provider and the type of
        telephony operation (SMS or Voice). For `sms` and `call`, you can select
        one method per telephony operation (`sms` and `call`) for sending
        messages or voice calls.


        > **Note:** Configure your telephony provider settings before selecting
        the methods for sending SMS messages or making voice calls. For example,
        if you select Twilio as your telephony provider, and you want to send
        SMS messages using Twilio's Verify Service, ensure that you have the
        Verify Service set up in your Twilio account. You can then use the
        `twilioVerifySid` field under `sms` to provide the necessary SID.
      type: object
      properties:
        call:
          description: >-
            Method for making voice calls. Choose one method for making voice
            calls based on your telephony provider setup.
          title: Twilio Verify SID
          type: object
          properties:
            twilioVerifySid:
              type: string
              description: >-
                The Twilio Verify Service SID used for sending verification
                messages or calls. You can find this value in your Twilio
                console.


                This method uses Twilio's [Verify
                API](https://www.twilio.com/docs/verify/api).
            twilioPhoneNumber:
              type: string
              description: >-
                The Twilio phone number that's used for sending SMS messages or
                voice calls. You can find this value in your Twilio console.


                This method uses Twilio's [Programmable Messaging
                API](https://www.twilio.com/docs/messaging).
            twilioCallerId:
              type: string
              description: >-
                The Twilio caller ID that's used for making calls. You can find
                this value in your Twilio console.


                This method uses Twilio's [Programmable Voice
                API](https://www.twilio.com/docs/voice).
            telesignService:
              type: string
              enum:
                - telesignVoiceService
                - telesignVerifyService
              description: >-
                The Telesign service identifier used for sending making calls.
                You can find this value in your Telesign console.


                The `telesignVerifyService` method uses Telesign's [Verify
                API](https://developer.telesign.com/enterprise/docs/verify-api-overview).
                And the `telesignVoiceService` method uses Telesign's [Voice
                API](https://developer.telesign.com/enterprise/docs/voice-overview).
        sms:
          description: >-
            Method for sending SMS messages. Choose one method for sending SMS
            messages based on your telephony provider setup.
          title: Twilio Verify SID
          type: object
          properties:
            twilioVerifySid:
              type: string
              description: >-
                The Twilio Verify Service SID used for sending verification
                messages or calls. You can find this value in your Twilio
                console.


                This method uses Twilio's [Verify
                API](https://www.twilio.com/docs/verify/api).
            twilioPhoneNumber:
              type: string
              description: >-
                The Twilio phone number that's used for sending SMS messages or
                voice calls. You can find this value in your Twilio console.


                This method uses Twilio's [Programmable Messaging
                API](https://www.twilio.com/docs/messaging).
            twilioMessageSid:
              type: string
              description: >-
                The Twilio Messaging Service SID used for sending SMS messages.
                You can find this value in your Twilio console.


                This method uses Twilio's [Programmable Messaging
                API](https://www.twilio.com/docs/messaging).
            telesignService:
              type: string
              enum:
                - telesignMessagingService
                - telesignVerifyService
              description: >-
                The Telesign service identifier used for sending SMS messages.
                You can find this value in your Telesign console.


                The `telesignVerifyService` method uses Telesign's [Verify
                API](https://developer.telesign.com/enterprise/docs/verify-api-overview).
                And the `telesignMessagingService` method uses Telesign's
                [SMS](https://developer.telesign.com/enterprise/docs/voice-overview)
                and
                [Messaging](https://developer.telesign.com/enterprise/docs/messaging-overview)
                APIs.
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
    CustomTelephonyProviderSettingsTwilioVerify:
      title: Twilio Verify SID
      type: object
      properties:
        twilioVerifySid:
          type: string
          description: >-
            The Twilio Verify Service SID used for sending verification messages
            or calls. You can find this value in your Twilio console.


            This method uses Twilio's [Verify
            API](https://www.twilio.com/docs/verify/api).
    CustomTelephonyProviderSettingsTwilioPhoneNumber:
      title: Twilio Phone Number
      type: object
      properties:
        twilioPhoneNumber:
          type: string
          description: >-
            The Twilio phone number that's used for sending SMS messages or
            voice calls. You can find this value in your Twilio console.


            This method uses Twilio's [Programmable Messaging
            API](https://www.twilio.com/docs/messaging).
    CustomTelephonyProviderSettingsTwilioCallerId:
      title: Twilio Caller ID
      type: object
      properties:
        twilioCallerId:
          type: string
          description: >-
            The Twilio caller ID that's used for making calls. You can find this
            value in your Twilio console.


            This method uses Twilio's [Programmable Voice
            API](https://www.twilio.com/docs/voice).
    CustomTelephonyProviderSettingsTelesignServiceCall:
      title: Telesign Service
      type: object
      properties:
        telesignService:
          type: string
          enum:
            - telesignVoiceService
            - telesignVerifyService
          description: >-
            The Telesign service identifier used for sending making calls. You
            can find this value in your Telesign console.


            The `telesignVerifyService` method uses Telesign's [Verify
            API](https://developer.telesign.com/enterprise/docs/verify-api-overview).
            And the `telesignVoiceService` method uses Telesign's [Voice
            API](https://developer.telesign.com/enterprise/docs/voice-overview).
    CustomTelephonyProviderSettingsTwilioMessagingService:
      title: Twilio Message SID
      type: object
      properties:
        twilioMessageSid:
          type: string
          description: >-
            The Twilio Messaging Service SID used for sending SMS messages. You
            can find this value in your Twilio console.


            This method uses Twilio's [Programmable Messaging
            API](https://www.twilio.com/docs/messaging).
    CustomTelephonyProviderSettingsTelesignServiceSms:
      title: Telesign Service
      type: object
      properties:
        telesignService:
          type: string
          enum:
            - telesignMessagingService
            - telesignVerifyService
          description: >-
            The Telesign service identifier used for sending SMS messages. You
            can find this value in your Telesign console.


            The `telesignVerifyService` method uses Telesign's [Verify
            API](https://developer.telesign.com/enterprise/docs/verify-api-overview).
            And the `telesignMessagingService` method uses Telesign's
            [SMS](https://developer.telesign.com/enterprise/docs/voice-overview)
            and
            [Messaging](https://developer.telesign.com/enterprise/docs/messaging-overview)
            APIs.
    ListAllCustomTelephonyProviderCredentialsResponse:
      type: object
      properties:
        custom_telephony_provider_credentials:
          type: array
          items:
            $ref: '#/components/schemas/CustomTelephonyProviderCredentialResponse'
  responses:
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
    ErrorResourceNotFound404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            ResourceNotFound:
              $ref: '#/components/examples/ErrorResourceNotFound'
    ErrorApiValidationFailed400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            APIValidationFailed:
              $ref: '#/components/examples/ErrorApiValidationFailed'
  parameters:
    customTelephonyProviderId:
      name: customTelephonyProviderId
      description: The ID of the custom telephony provider
      in: path
      required: true
      schema:
        type: string
  examples:
    CustomTelephonyProviderCredentialsListAllResponseEx:
      summary: List of custom telephony provider credentials
      value:
        - id: oct3v00k4iOFlEJmQ806
          isPrimaryProvider: true
          enabled: true
          providerCapability: ALL
          providerName: TWILIO
          providerSid: ACb49fb19a09b2f5d2f121fe1c207689dt
          providerSettings:
            sms:
              twilioPhoneNumber: '+1234567890'
            call:
              twilioVerifySid: example-verify-sid
        - id: oct3v00k4iOFlEG3dR45
          isPrimaryProvider: false
          enabled: true
          providerCapability: ALL
          providerName: TELESIGN
          providerSid: AC42tfy19a09b2f5d2f121fe1c207fg456r
          providerSettings:
            sms:
              telesignService: telesignMessagingService
            call:
              telesignService: telesignVerifyService
    CustomTelephonyProviderCredentialCreateRequestTwilioEx:
      summary: Create a Twilio custom telephony provider
      value:
        providerAuthToken: 11a9b6c435967abe806f4f0d6ec0f382
        providerCapability: ALL
        providerName: TWILIO
        providerSid: ACb49fb19a09b2f5d2f121fe1c207689dt
        providerSettings:
          sms:
            twilioPhoneNumber: '+1234567890'
          call:
            twilioVerifySid: example-verify-sid
    CustomTelephonyProviderCredentialCreateRequestTelesignEx:
      summary: Create a Telesign custom telephony provider
      value:
        providerAuthToken: 67bf6c435967abe806f4f0d6eg2p645
        providerCapability: ALL
        providerName: TELESIGN
        providerSid: CF98EDb19a09b2f5d2f121fe1c207722F7
        providerSettings:
          sms:
            telesignService: telesignMessagingService
          call:
            telesignService: telesignVerifyService
    CustomTelephonyProviderCredentialCreateResponseTwilioEx:
      summary: Response for Twilio custom telephony provider
      value:
        id: oct3v00k4iOFlEJmQ806
        isPrimaryProvider: true
        enabled: true
        providerCapability: ALL
        providerName: TWILIO
        providerSid: ACb49fb19a09b2f5d2f121fe1c207689dt
        providerSettings:
          sms:
            twilioPhoneNumber: '+1234567890'
          call:
            twilioVerifySid: example-verify-sid
    CustomTelephonyProviderCredentialCreateResponseTelesignEx:
      summary: Response for Telesign custom telephony provider
      value:
        id: oct1ko8bzvN4smpBU0g5
        isPrimaryProvider: true
        enabled: true
        providerCapability: ALL
        providerName: TELESIGN
        providerSid: ACl82fb19a09b2b422f121fe1c2076ch29
        providerSettings:
          sms:
            telesignService: telesignMessagingService
          call:
            telesignService: telesignVoiceService
    CustomTelephonyProviderCredentialListOneResponseEx:
      summary: Response for credentials of one custom telephony provider
      value:
        id: oct3v00k4iOFlEJmQ806
        isPrimaryProvider: true
        enabled: true
        providerCapability: ALL
        providerName: TWILIO
        providerSid: ACb49fb19a09b2f5d2f121fe1c207689dt
        providerSettings:
          sms:
            twilioPhoneNumber: '+1234567890'
          call:
            twilioVerifySid: example-verify-sid
    CustomTelephonyProviderCredentialUpdateRequestEx:
      summary: Update custom telephony provider credentials
      value:
        id: oct3v00k4iOFlEJmQ806
        providerAuthToken: 11a9b6c435967abe806f4f0d6ec0f382
        providerSid: ACb49fb19a09b2f5d2f121fe1c207689dt
        providerSettings:
          sms:
            twilioPhoneNumber: '+1234567890'
          call:
            twilioVerifySid: updated-verify-sid
    CustomTelephonyProviderCredentialsUpdateResponseEx:
      summary: Response for updated custom telephony provider
      value:
        id: oct3v00k4iOFlEJmQ806
        isPrimaryProvider: true
        enabled: true
        providerCapability: ALL
        providerName: TWILIO
        providerSid: 11a9b6c435967abe806f4f0d6ec0f382
        providerSettings:
          sms:
            twilioPhoneNumber: '+1234567890'
          call:
            twilioVerifySid: updated-verify-sid
    CustomTelephonyProviderCredentialDeactivatedResponseEx:
      summary: Response for deactivated custom telephony provider
      value:
        id: oct3v00k4iOFlEJmQ806
        isPrimaryProvider: false
        enabled: false
        providerCapability: ALL
        providerName: TWILIO
        providerSid: ACb49fb19a09b2f5d2f121fe1c207689dt
        providerSettings:
          sms:
            twilioPhoneNumber: '+1234567890'
          call:
            twilioVerifySid: example-verify-sid
    CustomTelephonyProviderCredentialPrimaryResponseEx:
      summary: Response for setting primary custom telephony provider
      value:
        id: oct3v00k4iOFlEJmQ806
        isPrimaryProvider: true
        enabled: true
        providerCapability: ALL
        providerName: TWILIO
        providerSid: ACb49fb19a09b2f5d2f121fe1c207689dt
        providerSettings:
          sms:
            twilioPhoneNumber: '+1234567890'
          call:
            twilioVerifySid: example-verify-sid
    CustomTelephonyProviderCredentialSendTestRequestEx:
      summary: Send test SMS message
      value:
        factor: SMS
        phoneNumber: '+1234567890'
        countryCodeIso2: US
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
    ErrorResourceNotFound:
      summary: Resource Not Found
      value:
        errorCode: E0000007
        errorSummary: 'Not found: {0}'
        errorLink: E0000007
        errorId: sampleMlLvGUj_YD5v16vkYWY
        errorCauses: []
    ErrorApiValidationFailed:
      summary: API Validation Failed
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: {0}'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses: []
  x-stackQL-resources:
    telephony_providers:
      id: okta.telephony_providers.telephony_providers
      name: telephony_providers
      title: Telephony Providers
      methods:
        list_all_custom_telephony_provider_credentials:
          operation:
            $ref: '#/paths/~1api~1v1~1telephony-providers/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.custom_telephony_provider_credentials
            overrideMediaType: application/json
            schema_override:
              $ref: >-
                #/components/schemas/ListAllCustomTelephonyProviderCredentialsResponse
            transform:
              body: >-
                {{- $wrapped := printf
                "{\"custom_telephony_provider_credentials\":%s}" . -}}

                {{- $wrapped -}}
              type: golang_template_text_v0.3.0
        create_custom_telephony_provider_credentials:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1api~1v1~1telephony-providers/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        get_custom_telephony_provider_credential:
          operation:
            $ref: >-
              #/paths/~1api~1v1~1telephony-providers~1{customTelephonyProviderId}/get
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        update_custom_telephony_provider_credential:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: >-
              #/paths/~1api~1v1~1telephony-providers~1{customTelephonyProviderId}/patch
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete_custom_telephony_provider_credential:
          operation:
            $ref: >-
              #/paths/~1api~1v1~1telephony-providers~1{customTelephonyProviderId}/delete
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        activate_custom_telephony_credential:
          operation:
            $ref: >-
              #/paths/~1api~1v1~1telephony-providers~1{customTelephonyProviderId}~1lifecycle~1activate/post
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        deactivate_custom_telephony_credential:
          operation:
            $ref: >-
              #/paths/~1api~1v1~1telephony-providers~1{customTelephonyProviderId}~1lifecycle~1deactivate/post
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        set_as_primary_custom_telephony_credential:
          operation:
            $ref: >-
              #/paths/~1api~1v1~1telephony-providers~1{customTelephonyProviderId}~1setAsPrimary/post
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        send_test_custom_telephony_provider_credential:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: >-
              #/paths/~1api~1v1~1telephony-providers~1{customTelephonyProviderId}~1test/post
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/telephony_providers/methods/get_custom_telephony_provider_credential
          - $ref: >-
              #/components/x-stackQL-resources/telephony_providers/methods/list_all_custom_telephony_provider_credentials
        insert:
          - $ref: >-
              #/components/x-stackQL-resources/telephony_providers/methods/create_custom_telephony_provider_credentials
        update:
          - $ref: >-
              #/components/x-stackQL-resources/telephony_providers/methods/update_custom_telephony_provider_credential
        delete:
          - $ref: >-
              #/components/x-stackQL-resources/telephony_providers/methods/delete_custom_telephony_provider_credential
        replace: []
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
x-stackQL-config:
  pagination:
    requestToken:
      key: ''
      location: request
    responseToken:
      key: Link
      location: header
  queryParamPushdown:
    top:
      paramName: limit
      maxValue: 200
