openapi: 3.0.3
info:
  title: trustedorigins API
  description: okta trustedorigins API
  version: 5.1.0
paths:
  /api/v1/trustedOrigins:
    get:
      summary: List all trusted origins
      description: Lists all trusted origins
      operationId: listTrustedOrigins
      parameters:
        - name: q
          description: A search string that prefix matches against the `name` and `origin`
          in: query
          schema:
            type: string
        - name: filter
          description: >
            [Filter](https://developer.okta.com/docs/api/#filter) trusted
            origins with a supported expression for a subset of properties. You
            can filter on the following properties: `name`, `origin`, `status`,
            and `type` (type of scopes).
          in: query
          schema:
            type: string
          examples:
            By name:
              value: name eq "Example trusted origin"
        - name: after
          description: After cursor provided by a prior request
          in: query
          schema:
            type: string
        - name: limit
          description: Specifies the number of results
          in: query
          schema:
            type: integer
            format: int32
            default: 20
            maximum: 200
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrustedOrigin'
              examples:
                TrustedOriginsResponse:
                  $ref: '#/components/examples/TrustedOriginsResponse'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.trustedOrigins.read
      tags:
        - TrustedOrigin
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    post:
      summary: Create a trusted origin
      description: Creates a trusted origin
      operationId: createTrustedOrigin
      x-codegen-request-body-name: trustedOrigin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrustedOriginWrite'
            examples:
              TrustedOriginBody:
                $ref: '#/components/examples/TrustedOriginBody'
              TrustedOriginBodyWithIframeEmbedding:
                $ref: '#/components/examples/TrustedOriginBodyWithIframeEmbedding'
              TrustedOriginBodyWithIframeEmbeddingSignIn:
                $ref: >-
                  #/components/examples/TrustedOriginBodyWithIframeEmbeddingSignIn
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrustedOrigin'
              examples:
                TrustedOriginResponse:
                  $ref: '#/components/examples/TrustedOriginResponse'
                TrustedOriginResponseWithIframeEmbedding:
                  $ref: >-
                    #/components/examples/TrustedOriginResponseWithIframeEmbedding
                TrustedOriginResponseWithIframeEmbeddingSignIn:
                  $ref: >-
                    #/components/examples/TrustedOriginResponseWithIframeEmbeddingSignIn
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.trustedOrigins.manage
      tags:
        - TrustedOrigin
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
  /api/v1/trustedOrigins/{trustedOriginId}:
    get:
      summary: Retrieve a trusted origin
      description: Retrieves a trusted origin
      operationId: getTrustedOrigin
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrustedOrigin'
              examples:
                TrustedOriginResponse:
                  $ref: '#/components/examples/TrustedOriginResponse'
                TrustedOriginResponseWithIframeEmbedding:
                  $ref: >-
                    #/components/examples/TrustedOriginResponseWithIframeEmbedding
                TrustedOriginResponseWithIframeEmbeddingSignIn:
                  $ref: >-
                    #/components/examples/TrustedOriginResponseWithIframeEmbeddingSignIn
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.trustedOrigins.read
      tags:
        - TrustedOrigin
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    put:
      summary: Replace a trusted origin
      description: Replaces a trusted origin
      operationId: replaceTrustedOrigin
      x-codegen-request-body-name: trustedOrigin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrustedOrigin'
            examples:
              TrustedOriginPutBody:
                $ref: '#/components/examples/TrustedOriginPutBody'
              TrustedOriginPutBodyWithIframeEmbedding:
                $ref: '#/components/examples/TrustedOriginPutBodyWithIframeEmbedding'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrustedOrigin'
              examples:
                TrustedOriginPutResponse:
                  $ref: '#/components/examples/TrustedOriginPutResponse'
                TrustedOriginPutResponseWithIFrameEmbedding:
                  $ref: >-
                    #/components/examples/TrustedOriginPutResponseWithIframeEmbedding
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.trustedOrigins.manage
      tags:
        - TrustedOrigin
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    delete:
      summary: Delete a trusted origin
      description: Deletes a trusted origin
      operationId: deleteTrustedOrigin
      responses:
        '204':
          description: Success
          content: {}
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.trustedOrigins.manage
      tags:
        - TrustedOrigin
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    parameters:
      - $ref: '#/components/parameters/pathTrustedOriginId'
  /api/v1/trustedOrigins/{trustedOriginId}/lifecycle/activate:
    post:
      summary: Activate a trusted origin
      description: Activates a trusted origin. Sets the `status` to `ACTIVE`.
      operationId: activateTrustedOrigin
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrustedOrigin'
              examples:
                TrustedOriginResponse:
                  $ref: '#/components/examples/TrustedOriginResponse'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.trustedOrigins.manage
      tags:
        - TrustedOrigin
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    parameters:
      - $ref: '#/components/parameters/pathTrustedOriginId'
  /api/v1/trustedOrigins/{trustedOriginId}/lifecycle/deactivate:
    post:
      summary: Deactivate a trusted origin
      description: Deactivates a trusted origin. Sets the `status` to `INACTIVE`.
      operationId: deactivateTrustedOrigin
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrustedOrigin'
              examples:
                TrustedOriginInactiveResponse:
                  $ref: '#/components/examples/TrustedOriginInactiveResponse'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.trustedOrigins.manage
      tags:
        - TrustedOrigin
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    parameters:
      - $ref: '#/components/parameters/pathTrustedOriginId'
components:
  schemas:
    TrustedOrigin:
      type: object
      properties:
        created:
          description: Timestamp when the trusted origin was created
          type: string
          format: date-time
          readOnly: true
        createdBy:
          description: The ID of the user who created the trusted origin
          type: string
        id:
          description: Unique identifier for the trusted origin
          type: string
          readOnly: true
        lastUpdated:
          description: Timestamp when the trusted origin was last updated
          type: string
          format: date-time
          readOnly: true
        lastUpdatedBy:
          description: The ID of the user who last updated the trusted origin
          type: string
        name:
          $ref: '#/components/schemas/TrustedOriginName'
        origin:
          $ref: '#/components/schemas/TrustedOriginOrigin'
        scopes:
          $ref: '#/components/schemas/TrustedOriginScopes'
        status:
          $ref: '#/components/schemas/LifecycleStatus'
        _links:
          $ref: '#/components/schemas/LinksSelfAndLifecycle'
    TrustedOriginWrite:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/TrustedOriginName'
        origin:
          $ref: '#/components/schemas/TrustedOriginOrigin'
        scopes:
          $ref: '#/components/schemas/TrustedOriginScopes'
    TrustedOriginName:
      maximum: 255
      description: Unique name for the trusted origin
      type: string
    TrustedOriginOrigin:
      maximum: 255
      description: >-
        Unique origin URL for the trusted origin. The supported schemes for this
        attribute are HTTP, HTTPS, FTP, Ionic 2, and Capacitor.
      type: string
    TrustedOriginScopes:
      maximum: 3
      description: Array of scope types that this trusted origin is used for
      items:
        $ref: '#/components/schemas/TrustedOriginScope'
      type: array
    LifecycleStatus:
      type: string
      enum:
        - ACTIVE
        - INACTIVE
    LinksSelfAndLifecycle:
      allOf:
        - $ref: '#/components/schemas/LinksSelf'
        - type: object
          properties:
            activate:
              $ref: '#/components/schemas/HrefObjectActivateLink'
            deactivate:
              $ref: '#/components/schemas/HrefObjectDeactivateLink'
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: >-
            A unique identifier for this error. This can be used by Okta Support
            to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: >-
            A short description of what caused this error. Sometimes this
            contains dynamically-generated information about your specific
            error.
    TrustedOriginScope:
      type: object
      properties:
        allowedOktaApps:
          type: array
          description: The allowed Okta apps for the trusted origin scope
          items:
            $ref: '#/components/schemas/IframeEmbedScopeAllowedApps'
        type:
          $ref: '#/components/schemas/TrustedOriginScopeType'
    LinksSelf:
      description: >-
        Specifies link relations (see [Web
        Linking](https://www.rfc-editor.org/rfc/rfc8288)) available using the
        [JSON Hypertext Application
        Language](https://datatracker.ietf.org/doc/html/draft-kelly-json-hal-06)
        specification. This object is used for dynamic discovery of related
        resources and lifecycle operations.
      type: object
      properties:
        self:
          $ref: '#/components/schemas/HrefObjectSelfLink'
      readOnly: true
    HrefObjectActivateLink:
      allOf:
        - $ref: '#/components/schemas/HrefObject'
        - description: Link to activate the resource
    HrefObjectDeactivateLink:
      allOf:
        - $ref: '#/components/schemas/HrefObject'
        - description: Link to deactivate the resource
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
    IframeEmbedScopeAllowedApps:
      type: string
      enum:
        - OKTA_ENDUSER
    TrustedOriginScopeType:
      description: >
        The scope type. Supported values: When you use `IFRAME_EMBED` as the
        scope type, leave the `allowedOktaApps` property empty to allow iFrame
        embedding of only Okta sign-in pages. Include `OKTA_ENDUSER` as a value
        for the `allowedOktaApps` property to allow iFrame embedding of both
        Okta sign-in pages and the Okta End-User Dashboard.
      type: string
      enum:
        - CORS
        - IFRAME_EMBED
        - REDIRECT
    HrefObjectSelfLink:
      allOf:
        - $ref: '#/components/schemas/HrefObject'
        - description: Link to the resource (self)
    HrefObject:
      title: Link Object
      additionalProperties: true
      type: object
      properties:
        hints:
          $ref: '#/components/schemas/HrefHints'
          readOnly: true
        href:
          type: string
          description: Link URI
        name:
          type: string
          description: Link name
          readOnly: true
        templated:
          type: boolean
          description: >-
            Indicates whether the link object's `href` property is a URI
            template.
          readOnly: true
        type:
          type: string
          description: >-
            The media type of the link. If omitted, it is implicitly
            `application/json`.
          readOnly: true
      required:
        - href
    HrefHints:
      description: Describes allowed HTTP verbs for the `href`
      type: object
      properties:
        allow:
          type: array
          items:
            $ref: '#/components/schemas/HttpMethod'
    HttpMethod:
      type: string
      enum:
        - DELETE
        - GET
        - POST
        - PUT
  responses:
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
    ErrorTooManyRequests429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            TooManyRequests:
              $ref: '#/components/examples/ErrorTooManyRequests'
    ErrorApiValidationFailed400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            APIValidationFailed:
              $ref: '#/components/examples/ErrorApiValidationFailed'
    ErrorResourceNotFound404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            ResourceNotFound:
              $ref: '#/components/examples/ErrorResourceNotFound'
  parameters:
    pathTrustedOriginId:
      name: trustedOriginId
      description: '`id` of the trusted origin'
      in: path
      required: true
      schema:
        type: string
        example: 7j2PkU1nyNIDe26ZNufR
  examples:
    TrustedOriginsResponse:
      summary: Trusted origins response
      value:
        - id: tos10hu7rkbtrFt1M0g4
          name: New trusted origin
          origin: http://example.com
          status: ACTIVE
          scopes:
            - type: CORS
            - type: REDIRECT
          created: '2018-01-13T01:11:44.000Z'
          createdBy: 00ut5t92p6IEOi4bu0g3
          lastedUpdated: '2018-01-13T01:11:44.000Z'
          lastedUpdatedBy: 00ut5t92p6IEOi4bu0g3
          _links:
            self:
              href: >-
                https://{yourOktaDomain}/api/v1/trustedOrigins/tos10hu7rkbtrFt1M0g4
              hints:
                allow:
                  - GET
                  - PUT
                  - DELETE
            deactivate:
              href: >-
                https://{yourOktaDomain}/api/v1/trustedOrigins/tos10hu7rkbtrFt1M0g4/lifecycle/deactivate
              hints:
                allow:
                  - POST
    TrustedOriginBody:
      summary: Trusted origin request body
      value:
        name: New trusted origin
        origin: http://example.com
        scopes:
          - type: CORS
          - type: REDIRECT
    TrustedOriginBodyWithIframeEmbedding:
      summary: >-
        Trusted origin request body with iFrame embedding (Okta End-User
        Dashboard and Okta sign-in page)
      description: >
        Creates a new trusted origin for iFrame embedding of an Okta resource
        within that origin. In this example, the type of Okta resource is both
        the Okta End-User Dashboard and the Okta sign-in page.
      value:
        name: New trusted origin
        origin: http://example.com
        scopes:
          - type: IFRAME_EMBED
            allowedOktaApps:
              - OKTA_ENDUSER
    TrustedOriginBodyWithIframeEmbeddingSignIn:
      summary: Trusted origin request body with iFrame embedding (Okta sign-in page)
      description: >
        Creates a new trusted origin for iFrame embedding of an Okta resource
        within that origin. In this example, the Okta resource is the Okta
        sign-in page.
      value:
        name: New trusted origin
        origin: http://example.com
        scopes:
          - type: IFRAME_EMBED
            allowedOktaApps: []
    TrustedOriginResponse:
      summary: Trusted origin response
      value:
        id: tos10hu7rkbtrFt1M0g4
        name: New trusted origin
        origin: http://example.com
        status: ACTIVE
        scopes:
          - type: CORS
          - type: REDIRECT
        created: '2018-01-13T01:11:44.000Z'
        createdBy: 00ut5t92p6IEOi4bu0g3
        lastedUpdated: '2018-01-13T01:11:44.000Z'
        lastedUpdatedBy: 00ut5t92p6IEOi4bu0g3
        _links:
          self:
            href: >-
              https://{yourOktaDomain}/api/v1/trustedOrigins/tos10hu7rkbtrFt1M0g4
            hints:
              allow:
                - GET
                - PUT
                - DELETE
          deactivate:
            href: >-
              https://{yourOktaDomain}/api/v1/trustedOrigins/tos10hu7rkbtrFt1M0g4/lifecycle/deactivate
            hints:
              allow:
                - POST
    TrustedOriginResponseWithIframeEmbedding:
      summary: >-
        Trusted origin response with iFrame embedding (End-User Dashboard and
        Okta sign-in page)
      value:
        id: tos10hu7rkbtrFt1M0g4
        name: New trusted origin
        origin: http://example.com
        status: ACTIVE
        scopes:
          - type: IFRAME_EMBED
            allowedOktaApps:
              - OKTA_ENDUSER
        created: '2018-01-13T01:11:44.000Z'
        createdBy: 00ut5t92p6IEOi4bu0g3
        lastedUpdated: '2018-01-13T01:11:44.000Z'
        lastedUpdatedBy: 00ut5t92p6IEOi4bu0g3
        _links:
          self:
            href: >-
              https://{yourOktaDomain}/api/v1/trustedOrigins/tos10hu7rkbtrFt1M0g4
            hints:
              allow:
                - GET
                - PUT
                - DELETE
          deactivate:
            href: >-
              https://{yourOktaDomain}/api/v1/trustedOrigins/tos10hu7rkbtrFt1M0g4/lifecycle/deactivate
            hints:
              allow:
                - POST
    TrustedOriginResponseWithIframeEmbeddingSignIn:
      summary: Trusted origin response with iFrame embedding (Okta sign-in page)
      value:
        id: tos10hu7rkbtrFt1M0g4
        name: New trusted origin
        origin: http://example.com
        status: ACTIVE
        scopes:
          - type: IFRAME_EMBED
            allowedOktaApps: []
        created: '2018-01-13T01:11:44.000Z'
        createdBy: 00ut5t92p6IEOi4bu0g3
        lastedUpdated: '2018-01-13T01:11:44.000Z'
        lastedUpdatedBy: 00ut5t92p6IEOi4bu0g3
        _links:
          self:
            href: >-
              https://{yourOktaDomain}/api/v1/trustedOrigins/tos10hu7rkbtrFt1M0g4
            hints:
              allow:
                - GET
                - PUT
                - DELETE
          deactivate:
            href: >-
              https://{yourOktaDomain}/api/v1/trustedOrigins/tos10hu7rkbtrFt1M0g4/lifecycle/deactivate
            hints:
              allow:
                - POST
    TrustedOriginPutBody:
      summary: Trusted origin request body
      value:
        value:
          id: tosue7JvguwJ7U6kz0g3
          name: Updated Example trusted origin
          origin: http://updated.example.com
          scopes:
            - type: CORS
            - type: REDIRECT
          status: ACTIVE
          created: '2017-12-16T05:01:12.000Z'
          createdBy: 00ut5t92p6IEOi4bu0g3
          lastUpdated: '2017-12-16T05:01:12.000Z'
          lastUpdatedBy: 00ut5t92p6IEOi4bu0g3
          _links:
            self:
              href: >-
                https://${yourOktaDomain}/api/v1/trustedOrigins/tosue7JvguwJ7U6kz0g3
              hints:
                allow:
                  - GET
                  - PUT
                  - DELETE
            deactivate:
              href: >-
                https://${yourOktaDomain}/api/v1/trustedOrigins/tosue7JvguwJ7U6kz0g3/lifecycle/deactivate
              hints:
                allow:
                  - POST
    TrustedOriginPutBodyWithIframeEmbedding:
      summary: Trusted origin request body with iFrame embedding
      value:
        value:
          id: tosue7JvguwJ7U6kz0g3
          name: Updated trusted origin example
          origin: http://updated.example.com
          scopes:
            - type: IFRAME_EMBED
              allowedOktaApps:
                - OKTA_ENDUSER
          status: ACTIVE
          created: '2017-12-16T05:01:12.000Z'
          createdBy: 00ut5t92p6IEOi4bu0g3
          lastUpdated: '2017-12-16T05:01:12.000Z'
          lastUpdatedBy: 00ut5t92p6IEOi4bu0g3
          _links:
            self:
              href: >-
                https://${yourOktaDomain}/api/v1/trustedOrigins/tosue7JvguwJ7U6kz0g3
              hints:
                allow:
                  - GET
                  - PUT
                  - DELETE
            deactivate:
              href: >-
                https://${yourOktaDomain}/api/v1/trustedOrigins/tosue7JvguwJ7U6kz0g3/lifecycle/deactivate
              hints:
                allow:
                  - POST
    TrustedOriginPutResponse:
      summary: Trusted origin response body
      value:
        value:
          id: tosue7JvguwJ7U6kz0g3
          name: Updated Example trusted origin
          origin: http://updated.example.com
          scopes:
            - type: CORS
            - type: REDIRECT
          status: ACTIVE
          created: '2017-12-16T05:01:12.000Z'
          createdBy: 00ut5t92p6IEOi4bu0g3
          lastUpdated: '2017-12-16T05:01:12.000Z'
          lastUpdatedBy: 00ut5t92p6IEOi4bu0g3
          _links:
            self:
              href: >-
                https://${yourOktaDomain}/api/v1/trustedOrigins/tosue7JvguwJ7U6kz0g3
              hints:
                allow:
                  - GET
                  - PUT
                  - DELETE
            deactivate:
              href: >-
                https://${yourOktaDomain}/api/v1/trustedOrigins/tosue7JvguwJ7U6kz0g3/lifecycle/deactivate
              hints:
                allow:
                  - POST
    TrustedOriginPutResponseWithIframeEmbedding:
      summary: Trusted origin response body with iFrame embedding
      value:
        value:
          id: tosue7JvguwJ7U6kz0g3
          name: Updated trusted origin example
          origin: http://updated.example.com
          scopes:
            - type: IFRAME_EMBED
              allowedOktaApps:
                - OKTA_ENDUSER
          status: ACTIVE
          created: '2017-12-16T05:01:12.000Z'
          createdBy: 00ut5t92p6IEOi4bu0g3
          lastUpdated: '2017-12-16T05:01:12.000Z'
          lastUpdatedBy: 00ut5t92p6IEOi4bu0g3
          _links:
            self:
              href: >-
                https://${yourOktaDomain}/api/v1/trustedOrigins/tosue7JvguwJ7U6kz0g3
              hints:
                allow:
                  - GET
                  - PUT
                  - DELETE
            deactivate:
              href: >-
                https://${yourOktaDomain}/api/v1/trustedOrigins/tosue7JvguwJ7U6kz0g3/lifecycle/deactivate
              hints:
                allow:
                  - POST
    TrustedOriginInactiveResponse:
      summary: Trusted origin response
      value:
        id: tos10hu7rkbtrFt1M0g4
        name: New trusted origin
        origin: http://example.com
        status: INACTIVE
        scopes:
          - type: CORS
          - type: REDIRECT
        created: '2018-01-13T01:11:44.000Z'
        createdBy: 00ut5t92p6IEOi4bu0g3
        lastedUpdated: '2018-01-13T01:11:44.000Z'
        lastedUpdatedBy: 00ut5t92p6IEOi4bu0g3
        _links:
          activate:
            href: >-
              https://{yourOktaDomain}/api/v1/trustedOrigins/tos10hu7rkbtrFt1M0g4/lifecycle/activate
            hints:
              allow:
                - POST
          self:
            href: >-
              https://{yourOktaDomain}/api/v1/trustedOrigins/tos10hu7rkbtrFt1M0g4
            hints:
              allow:
                - GET
                - PUT
                - DELETE
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
    ErrorTooManyRequests:
      summary: Too Many Requests
      value:
        errorCode: E0000047
        errorSummary: API call exceeded rate limit due to too many requests.
        errorLink: E0000047
        errorId: sampleQPivGUj_ND5v78vbYWW
        errorCauses: []
    ErrorApiValidationFailed:
      summary: API Validation Failed
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: {0}'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses: []
    ErrorResourceNotFound:
      summary: Resource Not Found
      value:
        errorCode: E0000007
        errorSummary: 'Not found: {0}'
        errorLink: E0000007
        errorId: sampleMlLvGUj_YD5v16vkYWY
        errorCauses: []
  x-stackQL-resources:
    trusted_origins:
      id: okta.trustedorigins.trusted_origins
      name: trusted_origins
      title: Trusted Origins
      methods:
        list_trusted_origins:
          operation:
            $ref: '#/paths/~1api~1v1~1trustedOrigins/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        create_trusted_origin:
          operation:
            $ref: '#/paths/~1api~1v1~1trustedOrigins/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        get_trusted_origin:
          operation:
            $ref: '#/paths/~1api~1v1~1trustedOrigins~1{trustedOriginId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        replace_trusted_origin:
          operation:
            $ref: '#/paths/~1api~1v1~1trustedOrigins~1{trustedOriginId}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete_trusted_origin:
          operation:
            $ref: '#/paths/~1api~1v1~1trustedOrigins~1{trustedOriginId}/delete'
          response:
            mediaType: ''
            openAPIDocKey: '204'
        activate_trusted_origin:
          operation:
            $ref: >-
              #/paths/~1api~1v1~1trustedOrigins~1{trustedOriginId}~1lifecycle~1activate/post
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        deactivate_trusted_origin:
          operation:
            $ref: >-
              #/paths/~1api~1v1~1trustedOrigins~1{trustedOriginId}~1lifecycle~1deactivate/post
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/trusted_origins/methods/list_trusted_origins
          - $ref: >-
              #/components/x-stackQL-resources/trusted_origins/methods/get_trusted_origin
        insert:
          - $ref: >-
              #/components/x-stackQL-resources/trusted_origins/methods/create_trusted_origin
        update: []
        delete:
          - $ref: >-
              #/components/x-stackQL-resources/trusted_origins/methods/delete_trusted_origin
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/trusted_origins/methods/replace_trusted_origin
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
        description: >-
          The domain of your organization. This can be a provided subdomain of
          an official okta domain (okta.com, oktapreview.com, etc) or one of
          your configured custom domains.
