openapi: 3.0.3
info:
  title: zones API
  description: okta zones API
  version: 5.1.0
paths:
  /api/v1/zones:
    get:
      summary: List all network zones
      description: >-
        Lists all Network Zones with pagination. A subset of zones can be
        returned that match a supported filter expression or query.


        This operation requires URL encoding. For example, `filter=(id eq
        "nzoul0wf9jyb8xwZm0g3" or id eq "nzoul1MxmGN18NDQT0g3")` is encoded as
        `filter=%28id+eq+%22nzoul0wf9jyb8xwZm0g3%22+or+id+eq+%22nzoul1MxmGN18NDQT0g3%22%29`.


        Okta supports filtering on the `id`, `usage`, and `system` properties.
        See [Filter](https://developer.okta.com/docs/api/#filter) for more
        information on the expressions that are used in filtering.
      operationId: listNetworkZones
      parameters:
        - name: after
          in: query
          schema:
            type: string
            description: Specifies the pagination cursor for the next page of Network Zones
            example: BlockedIpZones
        - name: limit
          in: query
          schema:
            type: integer
            description: Specifies the number of results for a page
            format: int32
            example: 5
            default: -1
        - name: filter
          in: query
          schema:
            type: string
            description: Filters zones by usage, ID, or system expression
            example: id eq "nzowc1U5Jh5xuAK0o0g3"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NetworkZone'
              examples:
                RetrieveAllZonesWithFilter:
                  $ref: '#/components/examples/RetrieveAllZonesWithFilter'
                RetrieveAllZones:
                  $ref: '#/components/examples/RetrieveAllZones'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.networkZones.read
      tags:
        - NetworkZone
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    post:
      summary: Create a network zone
      description: >-
        Creates a Network Zone

        * For an IP Network Zone, you must define either `gateways` or
        `proxies`.

        * For a Dynamic Network Zone, you must define at least one of the
        following: `asns`, `locations`, or `proxyType`.

        * For an Enhanced Dynamic Network Zone, you must define at least one of
        the following: `asns`, `locations`, or `ipServiceCategories`.
      operationId: createNetworkZone
      x-codegen-request-body-name: zone
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetworkZone'
            examples:
              CreateIPPolicyNetworkZone:
                $ref: '#/components/examples/CreateIPPolicyNetworkZone'
              CreateIPPolicyBlocklistNetworkZone:
                $ref: '#/components/examples/CreateIPPolicyBlockListNetworkZone'
              CreateEDNetworkZone:
                $ref: '#/components/examples/CreateEDNZRequest'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkZone'
              examples:
                CreateIPPolicyNetworkZone:
                  $ref: '#/components/examples/CreateIPPolicyNetworkZoneResponse'
                CreateIPPolicyBlocklistNetworkZone:
                  $ref: >-
                    #/components/examples/CreateIPPolicyBlockListNetworkZoneResponse
                CreateEDNetworkZone:
                  $ref: '#/components/examples/CreateEDNZResponse'
        '400':
          $ref: '#/components/responses/NzErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.networkZones.manage
      tags:
        - NetworkZone
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
  /api/v1/zones/{zoneId}:
    get:
      summary: Retrieve a network zone
      description: Retrieves a Network Zone by `zoneId`
      operationId: getNetworkZone
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkZone'
              examples:
                RetrieveNetworkZoneIP:
                  $ref: '#/components/examples/RetrieveNetworkZoneIP'
                RetrieveNetworkZoneDynamic:
                  $ref: '#/components/examples/RetrieveNetworkZoneDynamic'
                RetrieveNetworkZoneEnhancedDynamic:
                  $ref: '#/components/examples/CreateEDNZResponse'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/NzErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.networkZones.read
      tags:
        - NetworkZone
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    put:
      summary: Replace a network zone
      description: >-
        Replaces a Network Zone by `zoneId`. The replaced Network Zone type must
        be the same as the existing type.

        You can replace the usage (`POLICY`, `BLOCKLIST`) of a Network Zone by
        updating the `usage` attribute.


        **IP exempt zone**<br>

        If you have the IP exempt zone feature enabled, you can allow traffic
        from specific gateway IPs irrespective of Okta ThreatInsight
        configurations, blocked network zones, or IP change events within
        Identity Threat Protection with Okta AI.<br>

        <br>

        When you enable this feature, Okta creates a zone called
        `DefaultExemptIpZone`. Gateway IPs that you add to this zone always have
        access to Okta resources. See [IP exempt
        zone](https://help.okta.com/okta_help.htm?type=oie&id=csh-about-ip-exempt-zone).


        > **Note:** You can't add trusted proxy IPs to this zone, delete the
        zone, or create additional exempt IP zones.
      operationId: replaceNetworkZone
      x-codegen-request-body-name: zone
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetworkZone'
            examples:
              ReplaceNetworkZone:
                $ref: '#/components/examples/ReplaceNetworkZone'
              UpdateDefaultExemptIpZone:
                $ref: '#/components/examples/UpdateDefaultExemptIpZone'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkZone'
              examples:
                ReplaceNetworkZone:
                  $ref: '#/components/examples/ReplaceNetworkZoneResponse'
                UpdateDefaultExemptIpZoneResponse:
                  $ref: '#/components/examples/UpdateDefaultExemptIpZoneResponse'
        '400':
          $ref: '#/components/responses/NzErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/NzErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.networkZones.manage
      tags:
        - NetworkZone
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    delete:
      summary: Delete a network zone
      description: >-
        Deletes a Network Zone by `zoneId`

        > **Notes:**

        > * You can't delete a Network Zone that's used by a
        [Policy](https://developer.okta.com/docs/apihttps://developer.okta.com/docs/apihttps://developer.okta.com/docs/apihttps://developer.okta.com/docs/apihttps://developer.okta.com/docs/api/openapi/okta-management/management/tag/Policy/)
        or
        [Rule](https://developer.okta.com/docs/apihttps://developer.okta.com/docs/apihttps://developer.okta.com/docs/apihttps://developer.okta.com/docs/apihttps://developer.okta.com/docs/api/openapi/okta-management/management/tag/Policy/#tag/Policy/operation/listPolicyRules).

        > * For Okta Identity Engine orgs, you can't delete a Network Zone with
        an ACTIVE `status`. <x-lifecycle class="oie"></x-lifecycle>
      operationId: deleteNetworkZone
      responses:
        '204':
          description: No Content
          content: {}
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/NzErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.networkZones.manage
      tags:
        - NetworkZone
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    parameters:
      - $ref: '#/components/parameters/pathZoneId'
  /api/v1/zones/{zoneId}/lifecycle/activate:
    post:
      summary: Activate a network zone
      description: Activates a Network Zone by `zoneId`
      operationId: activateNetworkZone
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkZone'
              examples:
                ActivateNetworkZone:
                  $ref: '#/components/examples/ActivateNetworkZone'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/NzErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.networkZones.manage
      tags:
        - NetworkZone
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    parameters:
      - $ref: '#/components/parameters/pathZoneId'
  /api/v1/zones/{zoneId}/lifecycle/deactivate:
    post:
      summary: Deactivate a network zone
      description: Deactivates a Network Zone by `zoneId`
      operationId: deactivateNetworkZone
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkZone'
              examples:
                DeactivateNetworkZone:
                  $ref: '#/components/examples/DeactivateNetworkZone'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/NzErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.networkZones.manage
      tags:
        - NetworkZone
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    parameters:
      - $ref: '#/components/parameters/pathZoneId'
components:
  schemas:
    NetworkZone:
      type: object
      properties:
        created:
          type: string
          format: date-time
          description: Timestamp when the object was created
          readOnly: true
        id:
          type: string
          description: Unique identifier for the Network Zone
          readOnly: true
        lastUpdated:
          type: string
          format: date-time
          description: Timestamp when the object was last modified
          readOnly: true
        name:
          type: string
          description: Unique name for this Network Zone
          maxLength: 128
        status:
          $ref: '#/components/schemas/NetworkZoneStatus'
        system:
          type: boolean
          readOnly: true
          description: >
            Indicates a system Network Zone:

            * `true` for system Network Zones

            * `false` for custom Network Zones


            The Okta org provides the following default system Network Zones:

            * `LegacyIpZone`

            * `BlockedIpZone`

            * `DefaultEnhancedDynamicZone`

            * `DefaultExemptIpZone`


            Admins can modify the name of the default system Network Zone and
            add up to 5000 gateway or proxy IP entries.
        type:
          $ref: '#/components/schemas/NetworkZoneType'
        usage:
          $ref: '#/components/schemas/NetworkZoneUsage'
        _links:
          $ref: '#/components/schemas/LinksSelfAndLifecycle'
      required:
        - name
        - type
      discriminator:
        propertyName: type
        mapping:
          IP: '#/components/schemas/IPNetworkZone'
          DYNAMIC: '#/components/schemas/DynamicNetworkZone'
          DYNAMIC_V2: '#/components/schemas/EnhancedDynamicNetworkZone'
    NetworkZoneStatus:
      description: Network Zone status
      type: string
      enum:
        - ACTIVE
        - INACTIVE
    NetworkZoneType:
      description: The type of Network Zone
      type: string
      enum:
        - DYNAMIC
        - IP
        - DYNAMIC_V2
    NetworkZoneUsage:
      description: The usage of the Network Zone
      type: string
      enum:
        - BLOCKLIST
        - POLICY
    LinksSelfAndLifecycle:
      allOf:
        - $ref: '#/components/schemas/LinksSelf'
        - type: object
          properties:
            activate:
              $ref: '#/components/schemas/HrefObjectActivateLink'
            deactivate:
              $ref: '#/components/schemas/HrefObjectDeactivateLink'
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: >-
            A unique identifier for this error. This can be used by Okta Support
            to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: >-
            A short description of what caused this error. Sometimes this
            contains dynamically-generated information about your specific
            error.
    LinksSelf:
      description: >-
        Specifies link relations (see [Web
        Linking](https://www.rfc-editor.org/rfc/rfc8288)) available using the
        [JSON Hypertext Application
        Language](https://datatracker.ietf.org/doc/html/draft-kelly-json-hal-06)
        specification. This object is used for dynamic discovery of related
        resources and lifecycle operations.
      type: object
      properties:
        self:
          $ref: '#/components/schemas/HrefObjectSelfLink'
      readOnly: true
    HrefObjectActivateLink:
      allOf:
        - $ref: '#/components/schemas/HrefObject'
        - description: Link to activate the resource
    HrefObjectDeactivateLink:
      allOf:
        - $ref: '#/components/schemas/HrefObject'
        - description: Link to deactivate the resource
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
    HrefObjectSelfLink:
      allOf:
        - $ref: '#/components/schemas/HrefObject'
        - description: Link to the resource (self)
    HrefObject:
      title: Link Object
      additionalProperties: true
      type: object
      properties:
        hints:
          $ref: '#/components/schemas/HrefHints'
          readOnly: true
        href:
          type: string
          description: Link URI
        name:
          type: string
          description: Link name
          readOnly: true
        templated:
          type: boolean
          description: >-
            Indicates whether the link object's `href` property is a URI
            template.
          readOnly: true
        type:
          type: string
          description: >-
            The media type of the link. If omitted, it is implicitly
            `application/json`.
          readOnly: true
      required:
        - href
    HrefHints:
      description: Describes allowed HTTP verbs for the `href`
      type: object
      properties:
        allow:
          type: array
          items:
            $ref: '#/components/schemas/HttpMethod'
    HttpMethod:
      type: string
      enum:
        - DELETE
        - GET
        - POST
        - PUT
  responses:
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
    ErrorTooManyRequests429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            TooManyRequests:
              $ref: '#/components/examples/ErrorTooManyRequests'
    NzErrorApiValidationFailed400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            APIValidationFailed:
              $ref: '#/components/examples/NzErrorApiValidationFailed'
    NzErrorResourceNotFound404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            ResourceNotFound:
              $ref: '#/components/examples/NzErrorResourceNotFound'
  parameters:
    pathZoneId:
      name: zoneId
      in: path
      schema:
        type: string
      required: true
      description: '`id` of the Network Zone'
      example: nzowc1U5Jh5xuAK0o0g3
  examples:
    RetrieveAllZonesWithFilter:
      summary: Retrieves network zones with filter
      value:
        - type: IP
          id: nzowc1U5Jh5xuAK0o0g3
          name: MyIpZone
          status: ACTIVE
          usage: POLICY
          created: '2021-06-24T20:37:32.000Z'
          lastUpdated: '2021-06-24T20:37:32.000Z'
          system: false
          gateways:
            - type: CIDR
              value: 1.2.3.4/24
          proxies:
            - type: RANGE
              value: 3.3.4.5-3.3.4.15
          _links:
            self:
              href: https://{yourOktaDomain}/api/v1/zones/nzowc1U5Jh5xuAK0o0g3
              hints:
                allow:
                  - GET
                  - PUT
                  - DELETE
            deactivate:
              href: >-
                https://{yourOktaDomain}/api/v1/zones/nzowc1U5Jh5xuAK0o0g3/lifecycle/deactivate
              hints:
                allow:
                  - POST
    RetrieveAllZones:
      summary: Retrieves all network zones
      value:
        - type: DYNAMIC_V2
          id: nzok0oz2xYHOZtIch0g4
          name: testZone106
          status: ACTIVE
          usage: BLOCKLIST
          create: '2024-05-13T16:33:44.000Z'
          lastUpdated: '2024-05-13T16:33:44.000Z'
          system: false
          locations:
            include: []
            exclude: []
          asns:
            include: []
            exclude: []
          ipServiceCategories:
            include:
              - ALL_ANONYMIZERS
            exclude: []
          _links:
            self:
              href: http://{yourOktaDomain}/api/v1/zones/nzok0oz2xYHOZtIch0g4
              hints:
                allow:
                  - GET
                  - PUT
                  - DELETE
            deactivate:
              href: >-
                http://{yourOktaDomain}/api/v1/zones/nzok0oz2xYHOZtIch0g4/lifecycle/deactivate
              hints:
                allow:
                  - POST
        - type: DYNAMIC
          id: nzoy0ox5xADOZtKrh0g6
          name: test
          status: ACTIVE
          usage: POLICY
          created: '2022-05-19T15:33:32.000Z'
          lastUpdated: '2022-05-19T15:33:32.000Z'
          system: false
          locations:
            - country: AF
              region: AF-BGL
          proxyType: ANY
          asns:
            - '23457'
          _links:
            self:
              href: https://{yourOktaDomain}/api/v1/zones/nzoy0ox5xADOZtKrh0g6
              hints:
                allow:
                  - GET
                  - PUT
                  - DELETE
            deactivate:
              href: >-
                https://{yourOktaDomain}/api/v1/zones/nzoy0ox5xADOZtKrh0g6/lifecycle/deactivate
              hints:
                allow:
                  - POST
        - type: IP
          id: nzowc1U5Jh5xuAK0o0g3
          name: MyIpZone
          status: ACTIVE
          usage: POLICY
          created: '2021-06-24T20:37:32.000Z'
          lastUpdated: '2021-06-24T20:37:32.000Z'
          system: false
          gateways:
            - type: CIDR
              value: 1.2.3.4/24
          proxies:
            - type: RANGE
              value: 3.3.4.5-3.3.4.15
          _links:
            self:
              href: https://{yourOktaDomain}/api/v1/zones/nzowc1U5Jh5xuAK0o0g3
              hints:
                allow:
                  - GET
                  - PUT
                  - DELETE
            deactivate:
              href: >-
                https://{yourOktaDomain}/api/v1/zones/nzowc1U5Jh5xuAK0o0g3/lifecycle/deactivate
              hints:
                allow:
                  - POST
        - type: IP
          id: nzou3u0stMCmgOzXK1d6
          name: BlockedIpZone
          status: ACTIVE
          usage: BLOCKLIST
          created: '2021-06-09T21:32:46.000Z'
          lastUpdated: '2021-06-09T21:32:46.000Z'
          system: true
          gateways: null
          proxies: null
          _links:
            self:
              href: https://{yourOktaDomain}/api/v1/zones/nzou3u0stMCmgOzXK1d6
              hints:
                allow:
                  - GET
                  - PUT
                  - DELETE
            deactivate:
              href: >-
                https://{yourOktaDomain}/api/v1/zones/nzou3u0stMCmgOzXK1d6/lifecycle/deactivate
              hints:
                allow:
                  - POST
        - type: DYNAMIC_V2
          id: nzohcnxFrSgsiwyHp0g4
          name: DefaultEnhancedDynamicZone
          status: ACTIVE
          usage: BLOCKLIST
          created: '2024-05-06T19:12:29.000Z'
          lastUpdated: '2024-05-09T21:02:31.000Z'
          system: true
          locations:
            include: []
            exclude: []
          ipServiceCategories:
            include:
              - ALL_ANONYMIZERS
            exclue: []
          asns:
            include: []
            exclude: []
          _links:
            self:
              href: https://{yourOktaDomain}/api/v1/zones/nzou3u0stMCmgOzXK1d6
              hints:
                allow:
                  - GET
                  - PUT
                  - DELETE
            deactivate:
              href: >-
                https://{yourOktaDomain}/api/v1/zones/nzou3u0stMCmgOzXK1d6/lifecycle/deactivate
              hints:
                allow:
                  - POST
        - type: IP
          id: nzou3u0ssJfZjYsWL1d6
          name: LegacyIpZone
          status: ACTIVE
          usage: POLICY
          created: '2021-06-09T21:32:46.000Z'
          lastUpdated: '2021-06-09T21:32:46.000Z'
          system: true
          gateways: null
          proxies: null
          _links:
            self:
              href: https://{yourOktaDomain}/api/v1/zones/nzou3u0ssJfZjYsWL1d6
              hints:
                allow:
                  - GET
                  - PUT
                  - DELETE
            deactivate:
              href: >-
                https://{yourOktaDomain}/api/v1/zones/nzou3u0ssJfZjYsWL1d6/lifecycle/deactivate
              hints:
                allow:
                  - POST
    CreateIPPolicyNetworkZone:
      summary: Create an IP policy network zone
      value:
        type: IP
        name: newNetworkZone
        gateways:
          - type: CIDR
            value: 1.2.3.4/24
          - type: CIDR
            value: 2.3.4.5/24
        proxies:
          - type: CIDR
            value: 2.2.3.4/24
          - type: CIDR
            value: 3.3.4.5/24
    CreateIPPolicyBlockListNetworkZone:
      summary: Create an IP blocklist network zone
      value:
        type: IP
        name: newBlockListNetworkZone
        status: ACTIVE
        usage: BLOCKLIST
        gateways:
          - type: CIDR
            value: 1.2.3.4/24
          - type: CIDR
            value: 2.3.4.5/24
        proxies: null
    CreateEDNZRequest:
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: false
        SKUs: []
      summary: Create an enhanced dynamic network zone
      value:
        type: DYNAMIC_V2
        name: testZone106
        status: ACTIVE
        usage: BLOCKLIST
        locations:
          include: []
          exclude: []
        asns:
          include: []
          exclude: []
        ipServiceCategories:
          include:
            - ALL_ANONYMIZERS
          exclude: []
    CreateIPPolicyNetworkZoneResponse:
      summary: IP policy network zone
      value:
        type: IP
        id: nzowb8T5Jh5xuAJ0o0g7
        name: newNetworkZone
        status: ACTIVE
        usage: POLICY
        created: '2021-08-09T21:32:01.000Z'
        lastUpdated: '2021-08-09T21:32:01.000Z'
        system: false
        gateways:
          - type: CIDR
            value: 1.2.3.4/24'
          - type: CIDR
            value: 2.3.4.5/24
        proxies:
          - type: CIDR
            value: 2.2.3.4/24
          - type: CIDR
            value: 3.3.4.5/24
        _links:
          self:
            href: https://{yourOktaDomain}/api/v1/zones/nzowb8T5Jh5xuAJ0o0g7
            hints:
              allow:
                - GET
                - PUT
                - DELETE
          deactivate:
            href: >-
              https://{yourOktaDomain}/api/v1/zones/nzowb8T5Jh5xuAJ0o0g7/lifecycle/deactivate
            hints:
              allow:
                - POST
    CreateIPPolicyBlockListNetworkZoneResponse:
      summary: IP blocklist network zone
      value:
        type: IP
        id: nzo1qasnPb1kqEq0e0g4
        name: newBlockListNetworkzone
        status: ACTIVE
        usage: BLOCKLIST
        created: '2021-08-09T20:22:09.000Z'
        lastUpdated: '2021-08-09T20:22:09.000Z'
        system: false
        gateways:
          - type: CIDR
            value: 1.2.3.4/24
          - type: CIDR
            value: 2.3.4.5/24
        proxies: null
        _links:
          self:
            href: https://{yourOktaDomain}/api/v1/zones/nzo1qasnPb1kqEq0e0g4
            hints:
              allow:
                - GET
                - PUT
                - DELETE
          deactivate:
            href: >-
              https://{yourOktaDomain}/api/v1/zones/nzo1qasnPb1kqEq0e0g4/lifecycle/deactivate
            hints:
              allow:
                - POST
    CreateEDNZResponse:
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: false
        SKUs: []
      summary: Enhanced dynamic network zone
      value:
        type: DYNAMIC_V2
        id: nzok0oz2xYHOZtIch0g4
        name: testZone106
        status: ACTIVE
        usage: BLOCKLIST
        create: '2024-05-13T16:33:44.000Z'
        lastUpdated: '2024-05-13T16:33:44.000Z'
        system: false
        locations:
          include: []
          exclude: []
        asns:
          include: []
          exclude: []
        ipServiceCategories:
          include:
            - ALL_ANONYMIZERS
          exclude: []
        _links:
          self:
            href: http://{yourOktaDomain}/api/v1/zones/nzok0oz2xYHOZtIch0g4
            hints:
              allow:
                - GET
                - PUT
                - DELETE
          deactivate:
            href: >-
              http://{yourOktaDomain}/api/v1/zones/nzok0oz2xYHOZtIch0g4/lifecycle/deactivate
            hints:
              allow:
                - POST
    RetrieveNetworkZoneIP:
      summary: IP network zone
      value:
        type: IP
        id: nzowc1U5Jh5xuAK0o0g3
        name: MyIpZone
        status: ACTIVE
        usage: POLICY
        created: '2021-06-24T20:37:32.000Z'
        lastUpdated: '2021-06-24T20:37:32.000Z'
        system: false
        gateways:
          - type: CIDR
            value: 1.2.3.4/24
        proxies:
          - type: RANGE
            value: 3.3.4.5-3.3.4.15
        _links:
          self:
            href: https://{yourOktaDomain}/api/v1/zones/nzowc1U5Jh5xuAK0o0g3
            hints:
              allow:
                - GET
                - PUT
                - DELETE
          deactivate:
            href: >-
              https://{yourOktaDomain}/api/v1/zones/nzowc1U5Jh5xuAK0o0g3/lifecycle/deactivate
            hints:
              allow:
                - POST
    RetrieveNetworkZoneDynamic:
      summary: Dynamic network zone
      value:
        type: DYNAMIC
        id: nzoy0ox5xADOZtKrh0g6
        name: test
        status: ACTIVE
        usage: POLICY
        created: '2022-05-19T15:33:32.000Z'
        lastUpdated: '2022-05-19T15:33:32.000Z'
        system: false
        locations:
          - country: AF
            region: AF-BGL
        proxyType: ANY
        asns:
          - '23457'
        _links:
          self:
            href: https://{yourOktaDomain}/api/v1/zones/nzoy0ox5xADOZtKrh0g6
            hints:
              allow:
                - GET
                - PUT
                - DELETE
          deactivate:
            href: >-
              https://{yourOktaDomain}/api/v1/zones/nzoy0ox5xADOZtKrh0g6/lifecycle/deactivate
            hints:
              allow:
                - POST
    ReplaceNetworkZone:
      summary: Replace a network zone
      value:
        type: IP
        id: nzovw2rFz2YoqmvwZ0g9
        name: UpdatedNetZone
        status: ACTIVE
        system: false
        usage: POLICY
        gateways:
          - type: CIDR
            value: 10.2.3.4/24
          - type: CIDR
            value: 12.2.3.4/24
          - type: RANGE
            value: 13.4.5.6-13.4.5.8
          - type: CIDR
            value: 14.2.3.4/24
        proxies:
          - type: CIDR
            value: 12.2.3.4/24
          - type: CIDR
            value: 13.3.4.5/24
          - type: RANGE
            value: 14.4.5.6-14.4.5.8
          - type: RANGE
            value: 15.5.6.7/24-15.5.6.9
        _links:
          self:
            href: https://{yourOktaDomain}/api/v1/zones/nzovw2rFz2YoqmvwZ0g9
            hints:
              allow:
                - GET
                - PUT
                - DELETE
          deactivate:
            href: >-
              https://{yourOktaDomain}/api/v1/zones/nzovw2rFz2YoqmvwZ0g9/lifecycle/deactivate
            hints:
              allow:
                - POST
    UpdateDefaultExemptIpZone:
      summary: Update the DefaultExemptIpZone
      value:
        type: IP
        id: nzodufauoBZYt5fIB0w6
        name: DefaultExemptIpZone
        status: ACTIVE
        usage: POLICY
        useAsExemptList: true
        system: true
        gateways:
          - type: RANGE
            value: 1.1.1.16-1.1.1.16
        proxies: null
        _links:
          self:
            href: https://{yourOktaDomain}/api/v1/zones/nzodufauoBZYt5fIB0w6
            hints:
              allow:
                - GET
                - PUT
                - DELETE
          deactivate:
            href: >-
              https://{yourOktaDomain}/api/v1/zones/nzodufauoBZYt5fIB0w6/lifecycle/deactivate
            hints:
              allow:
                - POST
    ReplaceNetworkZoneResponse:
      summary: Replace network zone
      value:
        type: IP
        id: nzovw2rFz2YoqmvwZ0g9
        name: UpdatedNetZone
        status: ACTIVE
        usage: POLICY
        created: '2022-05-08T18:25:05.000Z'
        lastUpdated: '2022-05-10T13:15:22.000Z'
        system: false
        gateways:
          - type: CIDR
            value: 10.2.3.4/24
          - type: CIDR
            value: 12.2.3.4/24
          - type: RANGE
            value: 13.4.5.6-13.4.5.8
          - type: CIDR
            value: 14.2.3.4/24
        proxies:
          - type: CIDR
            value: 12.2.3.4/24
          - type: CIDR
            value: 13.3.4.5/24
          - type: RANGE
            value: 14.4.5.6-14.4.5.8
          - type: RANGE
            value: 15.5.6.7/24-15.5.6.9
        _links:
          self:
            href: https://{yourOktaDomain}/api/v1/zones/nzovw2rFz2YoqmvwZ0g9
            hints:
              allow:
                - GET
                - PUT
                - DELETE
          deactivate:
            href: >-
              https://{yourOktaDomain}/api/v1/zones/nzovw2rFz2YoqmvwZ0g9/lifecycle/deactivate
            hints:
              allow:
                - POST
    UpdateDefaultExemptIpZoneResponse:
      summary: Update the DefaultExemptIpZone response
      value:
        type: IP
        id: nzodufauoBZYt5fIB0w6
        name: DefaultExemptIpZone
        status: ACTIVE
        usage: POLICY
        created: '2024-10-08T16:35:21.000Z'
        lastUpdated: '2024-10-08T16:36:31.000Z'
        system: true
        useAsBlackList: false
        useAsExemptList: true
        gateways:
          - type: RANGE
            value: 1.1.1.16-1.1.1.16
        proxies: null
        _links:
          self:
            href: https://{yourOktaDomain}/api/v1/zones/nzodufauoBZYt5fIB0w6
            hints:
              allow:
                - GET
                - PUT
                - DELETE
          deactivate:
            href: >-
              https://{yourOktaDomain}/api/v1/zones/nzodufauoBZYt5fIB0w6/lifecycle/deactivate
            hints:
              allow:
                - POST
    ActivateNetworkZone:
      summary: Activated network zone
      value:
        type: IP
        id: nzowc1U5Jh5xuAK0o0g3
        name: MyIpZone
        status: ACTIVE
        usage: POLICY
        created: '2021-06-24T20:37:32.000Z'
        lastUpdated: '2021-06-24T20:37:32.000Z'
        system: false
        gateways:
          - type: CIDR
            value: 1.2.3.4/24
        proxies:
          - type: RANGE
            value: 3.3.4.5-3.3.4.15
        _links:
          self:
            href: https://{yourOktaDomain}/api/v1/zones/nzowc1U5Jh5xuAK0o0g3
            hints:
              allow:
                - GET
                - PUT
                - DELETE
          deactivate:
            href: >-
              https://{yourOktaDomain}/api/v1/zones/nzowc1U5Jh5xuAK0o0g3/lifecycle/deactivate
            hints:
              allow:
                - POST
    DeactivateNetworkZone:
      summary: Deactivated network zone
      value:
        type: IP
        id: nzowc1U5Jh5xuAK0o0g3
        name: MyIpZone
        status: INACTIVE
        usage: POLICY
        created: '2021-06-24T20:37:32.000Z'
        lastUpdated: '2021-06-24T20:37:32.000Z'
        system: false
        gateways:
          - type: CIDR
            value: 1.2.3.4/24
        proxies:
          - type: RANGE
            value: 3.3.4.5-3.3.4.15
        _links:
          self:
            href: https://{yourOktaDomain}/api/v1/zones/nzowc1U5Jh5xuAK0o0g3
            hints:
              allow:
                - GET
                - PUT
                - DELETE
          activate:
            href: >-
              https://{yourOktaDomain}/api/v1/zones/nzowc1U5Jh5xuAK0o0g3/lifecycle/activate
            hints:
              allow:
                - POST
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
    ErrorTooManyRequests:
      summary: Too Many Requests
      value:
        errorCode: E0000047
        errorSummary: API call exceeded rate limit due to too many requests.
        errorLink: E0000047
        errorId: sampleQPivGUj_ND5v78vbYWW
        errorCauses: []
    NzErrorApiValidationFailed:
      summary: API Validation Failed
      value:
        errorCode: E0000003
        errorSummary: The request body was not well-formed.
        errorLink: E0000003
        errorId: samplewNxQUR9iohr4QYlD0eg
        errorCauses: []
    NzErrorResourceNotFound:
      summary: Resource Not Found
      value:
        errorCode: E0000007
        errorSummary: 'Not found: Resource not found: itd (NetworkZone)'
        errorLink: E0000007
        errorId: samplejCSVaKFDkCMElmKQ
        errorCauses: []
  x-stackQL-resources:
    network_zones:
      id: okta.zones.network_zones
      name: network_zones
      title: Network Zones
      methods:
        list_network_zones:
          operation:
            $ref: '#/paths/~1api~1v1~1zones/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        create_network_zone:
          operation:
            $ref: '#/paths/~1api~1v1~1zones/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        get_network_zone:
          operation:
            $ref: '#/paths/~1api~1v1~1zones~1{zoneId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        replace_network_zone:
          operation:
            $ref: '#/paths/~1api~1v1~1zones~1{zoneId}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete_network_zone:
          operation:
            $ref: '#/paths/~1api~1v1~1zones~1{zoneId}/delete'
          response:
            mediaType: ''
            openAPIDocKey: '204'
        activate_network_zone:
          operation:
            $ref: '#/paths/~1api~1v1~1zones~1{zoneId}~1lifecycle~1activate/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        deactivate_network_zone:
          operation:
            $ref: '#/paths/~1api~1v1~1zones~1{zoneId}~1lifecycle~1deactivate/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/network_zones/methods/list_network_zones
          - $ref: >-
              #/components/x-stackQL-resources/network_zones/methods/get_network_zone
        insert:
          - $ref: >-
              #/components/x-stackQL-resources/network_zones/methods/create_network_zone
        update: []
        delete:
          - $ref: >-
              #/components/x-stackQL-resources/network_zones/methods/delete_network_zone
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/network_zones/methods/replace_network_zone
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
        description: >-
          The domain of your organization. This can be a provided subdomain of
          an official okta domain (okta.com, oktapreview.com, etc) or one of
          your configured custom domains.
