openapi: 3.0.0
info:
  version: 2024-12-19-stackql-generated
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  title: Databricks Oauth API
  description: OAuth Integrations
servers:
- url: https://accounts.cloud.databricks.com
paths:
  /api/2.0/accounts/{account_id}/oauth2/custom-app-integrations:
    post:
      operationId: custom-app-integrations-create
      externalDocs:
        url: https://docs.databricks.com/api/account/customappintegration/create
      x-stackQL-resource: custom_app_integrations
      x-stackQL-method: create
      x-stackQL-verb: insert
      x-numReqParams: 1
      parameters:
      - name: account_id
        required: true
        description: string
        in: path
      responses:
        '200':
          description: Request completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  client_id:
                    type: string
                  client_secret:
                    type: string
                  integration_id:
                    type: string
        '400':
          description: Request is invalid or malformed.
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '500':
          description: Internal error.
        '501':
          description: Operation is not implemented or is not supported/enabled in
            this service.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                redirect_urls:
                  type: Array of string
                name:
                  type: string
                confidential:
                  type: boolean
                scopes:
                  type: Array of string
                token_access_policy:
                  type: object
              example:
                summary: Create Tableau Cloud OAuth App Integration
                value:
                  name: Example Tableau Server
                  scopes:
                  - all-apis
                  - offline_access
                  token_access_policy:
                    access_token_ttl_in_minutes: 120
                    refresh_token_ttl_in_minutes: 200
                  redirect_urls:
                  - https://example.online.tableau.com/auth/add_oauth_token
                  confidential: true
      description: Create Custom OAuth App Integration.
    get:
      operationId: custom-app-integrations-list
      externalDocs:
        url: https://docs.databricks.com/api/account/customappintegration/list
      x-stackQL-resource: custom_app_integrations
      x-stackQL-method: list
      x-stackQL-verb: select
      x-numReqParams: 1
      parameters:
      - name: account_id
        required: true
        description: string
        in: path
      - name: page_token
        in: query
      - name: page_size
        in: query
      - name: include_creator_username
        in: query
      responses:
        '200':
          description: Request completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  apps:
                    type: array
                    items:
                      type: object
                      properties:
                        integration_id:
                          type: string
                        client_id:
                          type: string
                        redirect_urls:
                          type: array
                          items:
                            type: string
                        name:
                          type: string
                        confidential:
                          type: boolean
                        token_access_policy:
                          type: object
                          properties:
                            access_token_ttl_in_minutes:
                              type: integer
                            refresh_token_ttl_in_minutes:
                              type: integer
                        scopes:
                          type: array
                          items:
                            type: string
                        created_by:
                          type: integer
                        create_time:
                          type: string
                        creator_username:
                          type: string
                  next_page_token:
                    type: string
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '500':
          description: Internal error.
        '501':
          description: Operation is not implemented or is not supported/enabled in
            this service.
      x-stackQL-objectKey: $.apps
      description: Get the list of custom OAuth app integrations for the specified
        Databricks account
  /api/2.0/accounts/{account_id}/oauth2/custom-app-integrations/{integration_id}:
    delete:
      operationId: custom-app-integrations-delete
      externalDocs:
        url: https://docs.databricks.com/api/account/customappintegration/delete
      x-stackQL-resource: custom_app_integrations
      x-stackQL-method: delete
      x-stackQL-verb: delete
      x-numReqParams: 2
      parameters:
      - name: account_id
        required: true
        description: string
        in: path
      - name: integration_id
        required: true
        description: string
        in: path
      responses:
        '200':
          description: Request completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '404':
          description: Operation was performed on a resource that does not exist.
        '500':
          description: Internal error.
        '501':
          description: Operation is not implemented or is not supported/enabled in
            this service.
      description: Delete an existing Custom OAuth App Integration. You can retrieve
        the custom OAuth app integration via
    get:
      operationId: custom-app-integrations-get
      externalDocs:
        url: https://docs.databricks.com/api/account/customappintegration/get
      x-stackQL-resource: custom_app_integrations
      x-stackQL-method: get
      x-stackQL-verb: select
      x-numReqParams: 2
      parameters:
      - name: account_id
        required: true
        description: string
        in: path
      - name: integration_id
        required: true
        description: string
        in: path
      responses:
        '200':
          description: Request completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  integration_id:
                    type: string
                  client_id:
                    type: string
                  redirect_urls:
                    type: array
                    items:
                      type: string
                  name:
                    type: string
                  confidential:
                    type: boolean
                  token_access_policy:
                    type: object
                    properties:
                      access_token_ttl_in_minutes:
                        type: integer
                      refresh_token_ttl_in_minutes:
                        type: integer
                  scopes:
                    type: array
                    items:
                      type: string
                  created_by:
                    type: integer
                  create_time:
                    type: string
                  creator_username:
                    type: string
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '404':
          description: Operation was performed on a resource that does not exist.
        '500':
          description: Internal error.
        '501':
          description: Operation is not implemented or is not supported/enabled in
            this service.
      description: Gets the Custom OAuth App Integration for the given integration
        id.
    patch:
      operationId: custom-app-integrations-update
      externalDocs:
        url: https://docs.databricks.com/api/account/customappintegration/update
      x-stackQL-resource: custom_app_integrations
      x-stackQL-method: update
      x-stackQL-verb: update
      x-numReqParams: 2
      parameters:
      - name: account_id
        required: true
        description: string
        in: path
      - name: integration_id
        required: true
        description: string
        in: path
      responses:
        '200':
          description: Request completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '400':
          description: Request is invalid or malformed.
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '404':
          description: Operation was performed on a resource that does not exist.
        '500':
          description: Internal error.
        '501':
          description: Operation is not implemented or is not supported/enabled in
            this service.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                redirect_urls:
                  type: Array of string
                token_access_policy:
                  type: object
              example:
                value:
                  token_access_policy:
                    access_token_ttl_in_minutes: 120
                    refresh_token_ttl_in_minutes: 200
      description: Updates an existing custom OAuth App Integration. You can retrieve
        the custom OAuth app integration via
  /api/2.0/accounts/{account_id}/oauth2/published-apps:
    get:
      operationId: published-apps-list
      externalDocs:
        url: https://docs.databricks.com/api/account/oauthpublishedapps/list
      x-stackQL-resource: published_apps
      x-stackQL-method: list
      x-stackQL-verb: select
      x-numReqParams: 1
      parameters:
      - name: account_id
        required: true
        description: string
        in: path
      - name: page_token
        in: query
      - name: page_size
        in: query
      responses:
        '200':
          description: Request completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  apps:
                    type: array
                    items:
                      type: object
                      properties:
                        app_id:
                          type: string
                        client_id:
                          type: string
                        name:
                          type: string
                        description:
                          type: string
                        is_confidential_client:
                          type: boolean
                        redirect_urls:
                          type: array
                          items:
                            type: string
                        scopes:
                          type: array
                          items:
                            type: string
                  next_page_token:
                    type: string
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '500':
          description: Internal error.
        '501':
          description: Operation is not implemented or is not supported/enabled in
            this service.
      x-stackQL-objectKey: $.apps
      description: Get all the available published OAuth apps in Databricks.
  /api/2.0/accounts/{account_id}/oauth2/published-app-integrations:
    post:
      operationId: published-app-integrations-create
      externalDocs:
        url: https://docs.databricks.com/api/account/publishedappintegration/create
      x-stackQL-resource: published_app_integrations
      x-stackQL-method: create
      x-stackQL-verb: insert
      x-numReqParams: 1
      parameters:
      - name: account_id
        required: true
        description: string
        in: path
      responses:
        '200':
          description: Request completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  integration_id:
                    type: string
        '400':
          description: Request is invalid or malformed.
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '500':
          description: Internal error.
        '501':
          description: Operation is not implemented or is not supported/enabled in
            this service.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                app_id:
                  type: string
                token_access_policy:
                  type: object
              example:
                PowerBI:
                  summary: Enable PowerBI OAuth Login
                  value:
                    app_id: power-bi
                TableauDesktop:
                  summary: Enable Tableau Desktop OAuth Login
                  value:
                    app_id: tableau-desktop
      description: Create Published OAuth App Integration.
    get:
      operationId: published-app-integrations-list
      externalDocs:
        url: https://docs.databricks.com/api/account/publishedappintegration/list
      x-stackQL-resource: published_app_integrations
      x-stackQL-method: list
      x-stackQL-verb: select
      x-numReqParams: 1
      parameters:
      - name: account_id
        required: true
        description: string
        in: path
      - name: page_token
        in: query
      - name: page_size
        in: query
      responses:
        '200':
          description: Request completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  apps:
                    type: array
                    items:
                      type: object
                      properties:
                        app_id:
                          type: string
                        integration_id:
                          type: string
                        name:
                          type: string
                        token_access_policy:
                          type: object
                          properties:
                            access_token_ttl_in_minutes:
                              type: integer
                            refresh_token_ttl_in_minutes:
                              type: integer
                        created_by:
                          type: integer
                        create_time:
                          type: string
                  next_page_token:
                    type: string
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '500':
          description: Internal error.
        '501':
          description: Operation is not implemented or is not supported/enabled in
            this service.
      x-stackQL-objectKey: $.apps
      description: Get the list of published OAuth app integrations for the specified
        Databricks account
  /api/2.0/accounts/{account_id}/oauth2/published-app-integrations/{integration_id}:
    delete:
      operationId: published-app-integrations-delete
      externalDocs:
        url: https://docs.databricks.com/api/account/publishedappintegration/delete
      x-stackQL-resource: published_app_integrations
      x-stackQL-method: delete
      x-stackQL-verb: delete
      x-numReqParams: 2
      parameters:
      - name: account_id
        required: true
        description: string
        in: path
      - name: integration_id
        required: true
        description: string
        in: path
      responses:
        '200':
          description: Request completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '404':
          description: Operation was performed on a resource that does not exist.
        '500':
          description: Internal error.
        '501':
          description: Operation is not implemented or is not supported/enabled in
            this service.
      description: Delete an existing Published OAuth App Integration. You can retrieve
        the published OAuth app integration via
    get:
      operationId: published-app-integrations-get
      externalDocs:
        url: https://docs.databricks.com/api/account/publishedappintegration/get
      x-stackQL-resource: published_app_integrations
      x-stackQL-method: get
      x-stackQL-verb: select
      x-numReqParams: 2
      parameters:
      - name: account_id
        required: true
        description: string
        in: path
      - name: integration_id
        required: true
        description: string
        in: path
      responses:
        '200':
          description: Request completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  app_id:
                    type: string
                  integration_id:
                    type: string
                  name:
                    type: string
                  token_access_policy:
                    type: object
                    properties:
                      access_token_ttl_in_minutes:
                        type: integer
                      refresh_token_ttl_in_minutes:
                        type: integer
                  created_by:
                    type: integer
                  create_time:
                    type: string
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '404':
          description: Operation was performed on a resource that does not exist.
        '500':
          description: Internal error.
        '501':
          description: Operation is not implemented or is not supported/enabled in
            this service.
      description: Gets the Published OAuth App Integration for the given integration
        id.
    patch:
      operationId: published-app-integrations-update
      externalDocs:
        url: https://docs.databricks.com/api/account/publishedappintegration/update
      x-stackQL-resource: published_app_integrations
      x-stackQL-method: update
      x-stackQL-verb: update
      x-numReqParams: 2
      parameters:
      - name: account_id
        required: true
        description: string
        in: path
      - name: integration_id
        required: true
        description: string
        in: path
      responses:
        '200':
          description: Request completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '400':
          description: Request is invalid or malformed.
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '404':
          description: Operation was performed on a resource that does not exist.
        '500':
          description: Internal error.
        '501':
          description: Operation is not implemented or is not supported/enabled in
            this service.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token_access_policy:
                  type: object
              example:
                value:
                  token_access_policy:
                    access_token_ttl_in_minutes: 120
                    refresh_token_ttl_in_minutes: 200
      description: Updates an existing published OAuth App Integration. You can retrieve
        the published OAuth app integration via
  /api/2.0/accounts/{account_id}/servicePrincipals/{service_principal_id}/credentials/secrets:
    post:
      operationId: service-principal-secrets-create
      externalDocs:
        url: https://docs.databricks.com/api/account/serviceprincipalsecrets/create
      x-stackQL-resource: service_principal_secrets
      x-stackQL-method: create
      x-stackQL-verb: insert
      x-numReqParams: 2
      parameters:
      - name: account_id
        required: true
        description: string
        in: path
      - name: service_principal_id
        required: true
        description: int64
        in: path
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  secret:
                    type: string
                  secret_hash:
                    type: string
                  create_time:
                    type: string
                  update_time:
                    type: string
                  status:
                    type: string
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '404':
          description: Operation was performed on a resource that does not exist.
        '500':
          description: Internal error.
      description: Create a secret for the given service principal.
    get:
      operationId: service-principal-secrets-list
      externalDocs:
        url: https://docs.databricks.com/api/account/serviceprincipalsecrets/list
      x-stackQL-resource: service_principal_secrets
      x-stackQL-method: list
      x-stackQL-verb: select
      x-numReqParams: 2
      parameters:
      - name: account_id
        required: true
        description: string
        in: path
      - name: service_principal_id
        required: true
        description: int64
        in: path
      - name: page_token
        in: query
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  secrets:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        secret_hash:
                          type: string
                        create_time:
                          type: string
                        update_time:
                          type: string
                        status:
                          type: string
                  next_page_token:
                    type: string
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '404':
          description: Operation was performed on a resource that does not exist.
        '500':
          description: Internal error.
      x-stackQL-objectKey: $.secrets
      description: List all secrets associated with the given service principal. This
        operation only returns information about the secrets themselves and does not
        include the secret values.
  /api/2.0/accounts/{account_id}/servicePrincipals/{service_principal_id}/credentials/secrets/{secret_id}:
    delete:
      operationId: service-principal-secrets-delete
      externalDocs:
        url: https://docs.databricks.com/api/account/serviceprincipalsecrets/delete
      x-stackQL-resource: service_principal_secrets
      x-stackQL-method: delete
      x-stackQL-verb: delete
      x-numReqParams: 3
      parameters:
      - name: account_id
        required: true
        description: string
        in: path
      - name: service_principal_id
        required: true
        description: int64
        in: path
      - name: secret_id
        required: true
        description: string
        in: path
      responses:
        '200':
          description: The secret was successfully deleted.
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '404':
          description: Operation was performed on a resource that does not exist.
        '500':
          description: Internal error.
      description: Delete a secret from the given service principal.
components:
  x-stackQL-resources:
    custom_app_integrations:
      id: databricks_account.oauth.custom_app_integrations
      name: custom_app_integrations
      title: Custom_app_integrations
      methods:
        create:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1oauth2~1custom-app-integrations/post'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
        list:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1oauth2~1custom-app-integrations/get'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.apps
        delete:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1oauth2~1custom-app-integrations~1{integration_id}/delete'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
        get:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1oauth2~1custom-app-integrations~1{integration_id}/get'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
        update:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1oauth2~1custom-app-integrations~1{integration_id}/patch'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
        - $ref: '#/components/x-stackQL-resources/custom_app_integrations/methods/get'
        - $ref: '#/components/x-stackQL-resources/custom_app_integrations/methods/list'
        insert:
        - $ref: '#/components/x-stackQL-resources/custom_app_integrations/methods/create'
        update:
        - $ref: '#/components/x-stackQL-resources/custom_app_integrations/methods/update'
        replace: []
        delete:
        - $ref: '#/components/x-stackQL-resources/custom_app_integrations/methods/delete'
        exec: []
    published_apps:
      id: databricks_account.oauth.published_apps
      name: published_apps
      title: Published_apps
      methods:
        list:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1oauth2~1published-apps/get'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.apps
      sqlVerbs:
        select:
        - $ref: '#/components/x-stackQL-resources/published_apps/methods/list'
        insert: []
        update: []
        replace: []
        delete: []
        exec: []
    published_app_integrations:
      id: databricks_account.oauth.published_app_integrations
      name: published_app_integrations
      title: Published_app_integrations
      methods:
        create:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1oauth2~1published-app-integrations/post'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
        list:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1oauth2~1published-app-integrations/get'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.apps
        delete:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1oauth2~1published-app-integrations~1{integration_id}/delete'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
        get:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1oauth2~1published-app-integrations~1{integration_id}/get'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
        update:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1oauth2~1published-app-integrations~1{integration_id}/patch'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
        - $ref: '#/components/x-stackQL-resources/published_app_integrations/methods/get'
        - $ref: '#/components/x-stackQL-resources/published_app_integrations/methods/list'
        insert:
        - $ref: '#/components/x-stackQL-resources/published_app_integrations/methods/create'
        update:
        - $ref: '#/components/x-stackQL-resources/published_app_integrations/methods/update'
        replace: []
        delete:
        - $ref: '#/components/x-stackQL-resources/published_app_integrations/methods/delete'
        exec: []
    service_principal_secrets:
      id: databricks_account.oauth.service_principal_secrets
      name: service_principal_secrets
      title: Service_principal_secrets
      methods:
        create:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1servicePrincipals~1{service_principal_id}~1credentials~1secrets/post'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
        list:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1servicePrincipals~1{service_principal_id}~1credentials~1secrets/get'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.secrets
        delete:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1servicePrincipals~1{service_principal_id}~1credentials~1secrets~1{secret_id}/delete'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
        - $ref: '#/components/x-stackQL-resources/service_principal_secrets/methods/list'
        insert:
        - $ref: '#/components/x-stackQL-resources/service_principal_secrets/methods/create'
        update: []
        replace: []
        delete:
        - $ref: '#/components/x-stackQL-resources/service_principal_secrets/methods/delete'
        exec: []
